Put cursor.execute query vars into a tuple
cursor.execute expects (query, vars) instead of (query, *vars), so move
all the vars into a tuple.  Here is the traceback:

```
Traceback (most recent call last):
  File "remove_duplicate_minor_version_books.py", line 72, in <module>
    main()
  File "remove_duplicate_minor_version_books.py", line 64, in main
    ' in %s'.format(table), to_del)
TypeError: not all arguments converted during string formatting
```